### ISSUE TITLE
502 Bad Gateway for Game Archive Site

### ISSUE THREAD

**Issue by tatamu-fold** [ustclug/hackergame2018-writeups#12]
Failed to open https://hack2018.lug.ustc.edu.cn/

**Comment by taoky** [comment]
您好，比赛存档只保证维护三个月，目前已经关闭。README 之后会更新。

**Comment by tatamu-fold** [comment]
@taoky Thanks for your quick reply. So is there any place I can read the original questions?

**Comment by taoky** [comment]
题目的文件和源代码都在仓库中公开了，但是题目文案没有公开（不过网上可以搜到其他人收集的题目文案）。
